language: 'en-gb'
general:
  max_sethomes: 10
  teleport_warmup_time: 5
  teleport_request_expiry_time: 60
bungee_options:
  enable_bungee_mode: false
  server_id: 'server'
spawn_command:
  enabled: true
  position:
    world:
    x:
    y:
    z:
    yaw:
    pitch:
data_storage_options:
  storage_type: 'SQLite'
  table_names:
    player_data: 'huskhomes_player_data'
    locations_data: 'huskhomes_location_data'
    homes_data: 'huskhomes_home_data'
    warps_data: 'huskhomes_warp_data'