name: HuskHomes
version: ${project.version}
main: me.william278.huskhomes2.HuskHomes
api-version: 1.16
authors: [William278]
softdepend: [dynmap, Vault, BlueMap, Pl3xMap]
description: A powerful, intuitive and flexible teleportation suite
libraries: [mysql:mysql-connector-java:8.0.25]

commands:
  home:
    description: Teleport to one of your homes
    usage: /home <home>
    permission: huskhomes.home
  sethome:
    description: Set a new home with given name
    usage: /sethome <name>
    permission: huskhomes.sethome
  delhome:
    description: Delete a home you previously set
    usage: /delhome <name/all>
    permission: huskhomes.delhome
  edithome:
    description: Edit one of your homes
    usage: /edithome <home> <rename/description/location/public/private> [arguments]
    permission: huskhomes.edithome
  warp:
    description: Teleport to a warp
    usage: /warp <warp>
    permission: huskhomes.warp
  setwarp:
    description: Set a new warp with given name
    usage: /setwarp <name>
    permission: huskhomes.setwarp
  delwarp:
    description: Delete a warp
    usage: /delwarp <name/all>
    permission: huskhomes.delwarp
  editwarp:
    description: Edit a warp
    usage: /editwarp <warp> <rename/description/location> [arguments]
    permission: huskhomes.editwarp
  back:
    description: Return to your previous position, or where you died
    usage: /back
    permission: huskhomes.back
  homelist:
    description: Get a list of your homes
    usage: /homelist <page>
    permission: huskhomes.home
    aliases: [homes, listhomes]
  warplist:
    description: View the list of warps
    usage: /warplist <page>
    permission: huskhomes.warp
    aliases: [warps, listwarps]
  publichomelist:
    description: View the list of public homes
    usage: /publichomelist <page>
    permission: huskhomes.publichome
    aliases: [phomes, phomelist, listphomes, listpublichomes]
  publichome:
    description: Teleport to a public home
    usage: /publichome <owner.home>
    permission: huskhomes.publichome
    aliases: [phome]
  tp:
    description: Teleport to another player or location
    usage: /tp <player/coordinates>
    permission: huskhomes.tp
    aliases: [tpo]
  tphere:
    description: Teleport another player to you
    usage: /tphere <player>
    permission: huskhomes.tp
    aliases: [tpohere]
  tpa:
    description: Request to teleport to another player
    usage: /tpa <player>
    permission: huskhomes.tprequest
    aliases: [tprequest, tpask]
  tpahere:
    description: Request another player to teleport to you
    usage: /tpahere <player>
    permission: huskhomes.tprequest
    aliases: [tphererequest, tpaskhere]
  tpaccept:
    description: Accept teleport requests
    usage: /tpaccept
    permission: huskhomes.tprequest
    aliases: [tpyes]
  tpdeny:
    description: Deny teleport requests
    usage: /tpdeny
    permission: huskhomes.tprequest
    aliases: [tpno]
  tpignore:
    description: Ignore incoming teleport requests
    usage: /tpignore
    permission: huskhomes.tpignore
    aliases: [tpaignore, ignoretprequests]
  tpoffline:
    description: Teleport to where a player was last online
    usage: /tpoffline <player>
    permission: huskhomes.tpoffline
  rtp:
    description: Teleport randomly into the wild
    usage: /rtp
    permission: huskhomes.rtp
    aliases: [randomtp, randomteleport, wild]
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: huskhomes.spawn
  setspawn:
    description: Set the spawn position
    usage: /setspawn
    permission: huskhomes.spawn.set
  huskhomes:
    description: Plugin information & reload configs.
    usage: /huskhomes <about/update/reload/migrate>

permissions:
  huskhomes.*:
    description: Grants all HuskHomes permissions
    children:
      huskhomes.bypass_timers: true
      huskhomes.commands: true
      huskhomes.private_home_admin: true
  huskhomes.private_home_admin:
    description: Lets you access and edit private homes
    children:
      huskhomes.home.other: true
      huskhomes.edithome.other: true
      huskhomes.delhome.other: true
  huskhomes.bypass_timers:
    description: Bypass all timer restrictions.
    children:
      huskhomes.bypass_timer: true
      huskhomes.rtp.bypass_cooldown: true
  huskhomes.basic:
    description: Access a basic pack of commands, good for Survival servers
    children:
      huskhomes.home: true
      huskhomes.sethome: true
      huskhomes.delhome: true
      huskhomes.edithome: true
      huskhomes.edithome.public: true
      huskhomes.publichome: true
      huskhomes.back: true
      huskhomes.back.death: true
      huskhomes.tprequest: true
      huskhomes.spawn: true
      huskhomes.warp: true
  huskhomes.commands:
    description: Access all HuskHomes commands
    children:
      huskhomes.home: true
      huskhomes.sethome: true
      huskhomes.delhome: true
      huskhomes.edithome: true
      huskhomes.edithome.public: true
      huskhomes.publichome: true
      huskhomes.back: true
      huskhomes.back.death: true
      huskhomes.tp: true
      huskhomes.tprequest: true
      huskhomes.spawn: true
      huskhomes.spawn.set: true
      huskhomes.warp: true
      huskhomes.setwarp: true
      huskhomes.delwarp: true
      huskhomes.editwarp: true
      huskhomes.rtp: true
      huskhomes.about: true
      huskhomes.version_checker: true
      huskhomes.reload: true
  huskhomes.bypass_timer:
    description: Allows you to bypass the teleportation timer
    default: false
  huskhomes.home:
    description: Allows you to teleport to a home
    default: true
  huskhomes.home.other:
    description: Allows you to teleport to all player homes
    default: op
  huskhomes.sethome:
    description: Allows you to set homes
    default: true
  huskhomes.delhome:
    description: Allows you to delete a home
    default: true
  huskhomes.delhome.other:
    description: Allows you to delete any player home
    default: op
  huskhomes.delhome.all:
    description: Allows you to delete all your homes
    default: true
  huskhomes.warp:
    description: Allows you to teleport to a warp
    default: true
  huskhomes.warp.*:
    description: Lets you access all warps even if permission-restricted
    default: op
  huskhomes.setwarp:
    description: Allows you to set server warps
    default: op
  huskhomes.delwarp:
    description: Allows you to delete a server warp
    default: op
  huskhomes.delwarp.all:
    description: Allows you to delete all server warps
    default: op
  huskhomes.publichome:
    description: Allows you to teleport to public homes
    default: true
  huskhomes.edithome:
    description: Allows you to edit home settings
    default: true
  huskhomes.edithome.other:
    description: Allows you to edit home settings for any home
    default: op
  huskhomes.editwarp:
    description: Allows you to edit home information
    default: op
  huskhomes.back:
    description: Allows you to return to your last position
    default: true
  huskhomes.rtp:
    description: Allows you to randomly teleport
    default: true
  huskhomes.rtp.bypass_cooldown:
    description: Allows you to bypass the /rtp cooldown
    default: false
  huskhomes.about:
    description: View information about the plugin
    default: true
  huskhomes.reload:
    description: Reload the plugin configuration & messages files
    default: op
  huskhomes.version_checker:
    description: Check if the plugin is up-to-date
    default: op
  huskhomes.tp:
    description: Allows you to directly teleport to players or locations
    default: op
  huskhomes.tprequest:
    description: Allows you to request to teleport to a player
    default: true
  huskhomes.tpignore:
    description: Allows you to ingore teleport requests
    default: true
  huskhomes.tpoffline:
    description: Allows you to teleport to where players logged off
    default: op
  huskhomes.back.death:
    description: Allows you to return to where you died
    default: true
  huskhomes.spawn:
    description: Allows you to teleport to spawn
    default: true
  huskhomes.spawn.set:
    description: Allows you to set the spawn location
    default: op
  huskhomes.edithome.public:
    description: Allows you to make a home public
    default: true