name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
author: 'William278'
main: 'net.william278.huskhomes.BukkitHuskHomes'
version: '${version}'
api-version: 1.16
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'mysql:mysql-connector-java:8.0.30'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
  - 'org.apache.commons:commons-text:1.9'

commands:
  home:
    usage: /home <name>
  sethome:
    usage: /sethome <name>
  homelist:
    usage: /homelist [page]
    aliases: [homes]
  delhome:
    usage: /delhome <name>
  edithome:
    usage: /edithome <name> [rename|description|relocate|privacy] [args]
  publichome:
    usage: /publichome [<owner_name>.<home_name>]
    aliases:  [phome]
  publichomelist:
    usage: /publichomelist [page]
    aliases:  [phomelist, phomes]
  warp:
    usage: /warp <name>
  setwarp:
    usage: /setwarp <name>
  warplist:
    usage: /warplist [page]
    aliases: [warps]
  delwarp:
    usage: /delwarp <name>
  editwarp:
    usage: /editwarp <name> [rename|description|relocate] [args]
  back:
    usage: /back