name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
main: 'net.william278.huskhomes.HuskHomesBukkit'
version: '${version}'
commands:
  home:
    usage: /home <name>
  sethome:
    usage: /sethome <name>