name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
author: 'William278'
main: 'net.william278.huskhomes.HuskHomesBukkit'
version: '${version}'
api-version: 1.16
commands:
  home:
    usage: /home <name>
  sethome:
    usage: /sethome <name>
  homelist:
    usage: /homelist [page]