name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
author: 'William278'
main: 'net.william278.huskhomes.BukkitHuskHomes'
version: '${version}'
api-version: 1.16
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'mysql:mysql-connector-java:8.0.29'
  - 'org.xerial:sqlite-jdbc:3.36.0.3'
  - 'org.apache.commons:commons-text:1.9'

commands:
  home:
    usage: /home <name>
  sethome:
    usage: /sethome <name>
  homelist:
    usage: /homelist [page]
  delhome:
    usage: /delhome <name>
  publichome:
    usage: /publichome [<owner_name>.<home_name>]
  publichomelist:
    usage: /publichomelist [page]
  warp:
    usage: /warp <name>
  setwarp:
    usage: /setwarp <name>
  warplist:
    usage: /warplist [page]
  delwarp:
    usage: /delwarp <name>
  back:
    usage: /back